apiVersion: v1
kind: Service

metadata:
  name: postgres
  namespace: resolveai

spec:
  type: ClusterIP

  selector:
    app: resolveai-postgres

  ports:
    - name: postgres
      port: 5432
      targetPort: 5432