apiVersion: v1
kind: Service

metadata:
  name: ai-service
  namespace: resolveai

spec:
  type: ClusterIP

  selector:
    app: resolveai-ai-service

  ports:
    - name: http
      port: 8000
      targetPort: 8000